name: movie_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1
dependencies:
  cached_network_image: ^3.4.1  # A package to display images from the internet with caching support, improving performance and reducing load times.
  cupertino_icons: ^1.0.8        
  dio: ^5.7.0                    # used for making network requests 
  equatable: ^2.0.5              # A package that helps to implement value equality for Dart objects, making it easier to compare objects in state management.
  flutter:                       
    sdk: flutter
  flutter_bloc: ^8.1.6          # A library that provides a way to manage state 
  hive: ^2.2.3                   # A lightweight and fast key-value database for Flutter
  hive_flutter: ^1.1.0           # Provides Flutter-specific extensions for Hive
  shared_preferences: ^2.3.2     # A package for persisting simple data types
  shimmer: ^3.0.0                # A package that adds a shimmer effect 

dev_dependencies:
  build_runner: ^2.4.13          # A tool for running code generation and build processes in Dart
  flutter_lints: ^4.0.0        
  flutter_test:                 
    sdk: flutter
  hive_generator: ^2.0.1         # A code generator for Hive, allowing automatic generation of TypeAdapters for data models to enable storage in Hive.

flutter:
  uses-material-design: true
 